In [31]:
import pandas as pd
import numpy as np
query="""
   with AA_LTV_sub as  
 (
 select * from 
 (
Select A1.*,
activation_dt as start_dt,
date_trunc( activation_dt, Month) as Signup_month,
udf.LTV_SIGNUP_PLAN_CALC(signup_plan_cd) as signup_plan,
case when subscription_platform_cd in ('RECURLY','PSP') then 'RECURLY' else subscription_platform_cd end as subscription_platform,

--- clean version of trial period offered
udf.LTV_TRIAL_PERIOD_CALC(signup_plan_cd, signup_trial_period_desc, sku_cd, trial_start_dt, paid_start_dt) as Trial_Period
     
 from `i-dss-cdm-data-dev.ent_vw.subscription_fct` A1
where A1.src_system_id=115 
and subscription_platform_cd not in ('Apple iOS', 'Apple TV')    
and activation_dt<@till_date
and lower(signup_plan_cd) not like '%annual%' 
)  
where Trial_Period is not null
)


, LTV_stg2 as (
select ov.Signup_month,
ov.Trial_Period,
ov.signup_plan,
case when total_starts is null then 0 else total_starts end as total_starts,
Subs_Retained_1 ,
case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 77  MONTH)) then Subs_Retained_2 else 0 end as Subs_Retained_2,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 76  MONTH)) then Subs_Retained_3 else 0 end as Subs_Retained_3,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 75  MONTH)) then Subs_Retained_4 else 0 end as Subs_Retained_4,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 74  MONTH)) then Subs_Retained_5 else 0 end as Subs_Retained_5,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 73  MONTH)) then Subs_Retained_6 else 0 end as Subs_Retained_6,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 72  MONTH)) then Subs_Retained_7 else 0 end as Subs_Retained_7,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 71  MONTH)) then Subs_Retained_8 else 0 end as Subs_Retained_8,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 70  MONTH)) then Subs_Retained_9 else 0 end as Subs_Retained_9,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 69  MONTH)) then Subs_Retained_10 else 0 end as Subs_Retained_10,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 68  MONTH)) then Subs_Retained_11 else 0 end as Subs_Retained_11,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 67  MONTH)) then Subs_Retained_12 else 0 end as Subs_Retained_12,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 66  MONTH)) then Subs_Retained_13 else 0 end as Subs_Retained_13,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 65  MONTH)) then Subs_Retained_14 else 0 end as Subs_Retained_14,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 64  MONTH)) then Subs_Retained_15 else 0 end as Subs_Retained_15,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 63  MONTH)) then Subs_Retained_16 else 0 end as Subs_Retained_16,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 62  MONTH)) then Subs_Retained_17 else 0 end as Subs_Retained_17,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 61  MONTH)) then Subs_Retained_18 else 0 end as Subs_Retained_18,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 60  MONTH)) then Subs_Retained_19 else 0 end as Subs_Retained_19,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 59  MONTH)) then Subs_Retained_20 else 0 end as Subs_Retained_20,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 58  MONTH)) then Subs_Retained_21 else 0 end as Subs_Retained_21,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 57  MONTH)) then Subs_Retained_22 else 0 end as Subs_Retained_22,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 56  MONTH)) then Subs_Retained_23 else 0 end as Subs_Retained_23,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 55  MONTH)) then Subs_Retained_24 else 0 end as Subs_Retained_24,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 54  MONTH)) then Subs_Retained_25 else 0 end as Subs_Retained_25,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 53  MONTH)) then Subs_Retained_26 else 0 end as Subs_Retained_26,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 52  MONTH)) then Subs_Retained_27 else 0 end as Subs_Retained_27,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 51  MONTH)) then Subs_Retained_28 else 0 end as Subs_Retained_28,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 50  MONTH)) then Subs_Retained_29 else 0 end as Subs_Retained_29,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 49  MONTH)) then Subs_Retained_30 else 0 end as Subs_Retained_30,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 48  MONTH)) then Subs_Retained_31 else 0 end as Subs_Retained_31,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 47  MONTH)) then Subs_Retained_32 else 0 end as Subs_Retained_32,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 46  MONTH)) then Subs_Retained_33 else 0 end as Subs_Retained_33,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 45  MONTH)) then Subs_Retained_34 else 0 end as Subs_Retained_34,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 44  MONTH)) then Subs_Retained_35 else 0 end as Subs_Retained_35,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 43  MONTH)) then Subs_Retained_36 else 0 end as Subs_Retained_36,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 42  MONTH)) then Subs_Retained_37 else 0 end as Subs_Retained_37,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 41  MONTH)) then Subs_Retained_38 else 0 end as Subs_Retained_38,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 40  MONTH)) then Subs_Retained_39 else 0 end as Subs_Retained_39,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 39  MONTH)) then Subs_Retained_40 else 0 end as Subs_Retained_40,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 38  MONTH)) then Subs_Retained_41 else 0 end as Subs_Retained_41,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 37  MONTH)) then Subs_Retained_42 else 0 end as Subs_Retained_42,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 36  MONTH)) then Subs_Retained_43 else 0 end as Subs_Retained_43,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 35  MONTH)) then Subs_Retained_44 else 0 end as Subs_Retained_44,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 34  MONTH)) then Subs_Retained_45 else 0 end as Subs_Retained_45,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 33  MONTH)) then Subs_Retained_46 else 0 end as Subs_Retained_46,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 32  MONTH)) then Subs_Retained_47 else 0 end as Subs_Retained_47,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 31  MONTH)) then Subs_Retained_48 else 0 end as Subs_Retained_48,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 30  MONTH)) then Subs_Retained_49 else 0 end as Subs_Retained_49,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 29  MONTH)) then Subs_Retained_50 else 0 end as Subs_Retained_50,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 28  MONTH)) then Subs_Retained_51 else 0 end as Subs_Retained_51,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 27  MONTH)) then Subs_Retained_52 else 0 end as Subs_Retained_52,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 26  MONTH)) then Subs_Retained_53 else 0 end as Subs_Retained_53,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 25  MONTH)) then Subs_Retained_54 else 0 end as Subs_Retained_54,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 24  MONTH)) then Subs_Retained_55 else 0 end as Subs_Retained_55,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 23  MONTH)) then Subs_Retained_56 else 0 end as Subs_Retained_56,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 22  MONTH)) then Subs_Retained_57 else 0 end as Subs_Retained_57,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 21  MONTH)) then Subs_Retained_58 else 0 end as Subs_Retained_58,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 20  MONTH)) then Subs_Retained_59 else 0 end as Subs_Retained_59,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 19  MONTH)) then Subs_Retained_60 else 0 end as Subs_Retained_60,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 18  MONTH)) then Subs_Retained_61 else 0 end as Subs_Retained_61,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 17  MONTH)) then Subs_Retained_62 else 0 end as Subs_Retained_62,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 16  MONTH)) then Subs_Retained_63 else 0 end as Subs_Retained_63,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 15  MONTH)) then Subs_Retained_64 else 0 end as Subs_Retained_64,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 14  MONTH)) then Subs_Retained_65 else 0 end as Subs_Retained_65,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 13  MONTH)) then Subs_Retained_66 else 0 end as Subs_Retained_66,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 12  MONTH)) then Subs_Retained_67 else 0 end as Subs_Retained_67,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 11  MONTH)) then Subs_Retained_68 else 0 end as Subs_Retained_68,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 10  MONTH)) then Subs_Retained_69 else 0 end as Subs_Retained_69,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 9  MONTH)) then Subs_Retained_70 else 0 end as Subs_Retained_70,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 8  MONTH)) then Subs_Retained_71 else 0 end as Subs_Retained_71,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 7  MONTH)) then Subs_Retained_72 else 0 end as Subs_Retained_72,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 6  MONTH)) then Subs_Retained_73 else 0 end as Subs_Retained_73,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 5  MONTH)) then Subs_Retained_74 else 0 end as Subs_Retained_74,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 4  MONTH)) then Subs_Retained_75 else 0 end as Subs_Retained_75,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL 3  MONTH)) then Subs_Retained_76 else 0 end as Subs_Retained_76,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL  2   MONTH)) then Subs_Retained_77 else 0 end as Subs_Retained_77,
    case when ov.Signup_month< (SELECT DATE_ADD(@start_date, INTERVAL  1   MONTH)) then Subs_Retained_78 else 0 end as Subs_Retained_78,
    case when ov.Signup_month<@start_date then Subs_Retained_79 else 0 end as Subs_Retained_79

from 
(

select * from
 
 (
 
 Select t.*,running_sum as Cum_cancels ,
 begin_paid_subs as starting_paid_subs
 from 

  (
 select Signup_month,
Trial_Period,
signup_plan,
 subsequent_month
 from
       (
       select distinct t.Signup_month,signup_plan,Trial_Period from (select r.* from AA_LTV_sub r)  dt 
       cross join
	   (select DATE_TRUNC(day_dt,MONTH) as Signup_month from `i-dss-cdm-data-dev.dw_vw.days` where day_dt between @start_date and @end_date) t -- Change the date range here 
 
      )
      cross join 
      (
      select s.* from 
      (select row_number() over (order by day_dt) subsequent_month from `i-dss-cdm-data-dev.dw_vw.days`) s where subsequent_month <=  (SELECT DATE_DIFF(@end_date,@start_date,MONTH)+2)) sb -- change the subsequent months
      ) t
    
      left join (
	  select Signup_Month,
    Trial_Period,
    signup_plan,
            subsequent_month as mn,
            SUM (cancels) OVER (PARTITION BY  Signup_month,signup_plan,Trial_Period ORDER BY subsequent_month) AS running_sum
            from (
             select Signup_month,
             Trial_Period,
             signup_plan,
			 case when (Days_actv/30)<=1 then 1 else CEILING(Days_actv/30) end as subsequent_month,
			 sum(users) as cancels
			 from (
             select Signup_month, 
             Trial_Period,
             signup_plan,
			 Days_actv,
			 count(distinct subscription_guid ) as users
			 from 
                               (
                               select t.*, 
                               DATE_DIFF(cast(case when expiration_dt is null OR expiration_dt>=@till_date then @till_date else expiration_dt end as date), cast( start_dt as Date),DAY) +1 as Days_actv
							   from AA_LTV_sub t
 
                               ) a1 
                               where cast(expiration_dt as date)<=@till_date
                               group by Signup_month, Trial_Period,signup_plan,
                               Days_actv) a2
            group by Signup_month,Trial_Period,signup_plan,
            case when (Days_actv/30)<=1 then 1
       else CEILING(Days_actv/30) end
       ) a3 
       ) can
       on (t.Signup_month=can.Signup_month
       and t.subsequent_month=can.mn
       and t.Trial_Period=can.Trial_Period
       and t.signup_plan=can.signup_plan)    
        left join ( 
       select Signup_month,   
       Trial_Period,signup_plan,
       count(distinct subscription_guid) as begin_paid_subs
                               from 
                               (
                               select t.*, 
                               DATE_DIFF(cast(case when expiration_dt is null OR expiration_dt>=@till_date then @till_date  else expiration_dt end as date), cast( start_dt as Date),DAY) +1 as Days_actv
							   from AA_LTV_sub t
 
                               ) a1 
                               group by Signup_month    ,Trial_Period   ,signup_plan                   
                               ) a4
                               on (t.Signup_month=a4.Signup_month
                               and t.Trial_Period=a4.Trial_Period
                               and t.signup_plan=a4.signup_plan)
       ) a5
        PIVOT(SUM(starting_paid_subs-Cum_cancels) as subs_retained FOR subsequent_month in
        (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
        21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,
        39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,
        57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,
        75,76,77,78,79))
) ov
left join ( 
       select Signup_month,   
       Trial_Period,
       signup_plan,
       count(distinct subscription_guid ) as total_starts
                               from 
                               (
                               select t.*, 
                               DATE_DIFF(cast(case when expiration_dt is null OR expiration_dt>=@till_date then @till_date else expiration_dt end as date), cast( start_dt as Date),DAY) +1 as Days_actv
							   from AA_LTV_sub t
 
                               ) a1 
                               group by Signup_month,Trial_Period ,signup_plan                            
                               ) strt
                               on (ov.Signup_month=strt.Signup_month
                               and ov.Trial_Period=strt.Trial_Period
                               and ov.signup_plan=strt.signup_plan)
order by 2,1

)

-- select * from LTV_stg2
, LTV_stg3 as (
select Signup_month,Trial_Period,
signup_plan,
total_starts,
coalesce((lag(total_starts,1)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l1,
coalesce((lag(total_starts,2)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l2,
    coalesce((lag(total_starts,3)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l3,
    coalesce((lag(total_starts,4)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l4,
    coalesce((lag(total_starts,5)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l5,
    coalesce((lag(total_starts,6)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l6,
    coalesce((lag(total_starts,7)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l7,
    coalesce((lag(total_starts,8)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l8,
    coalesce((lag(total_starts,9)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l9,
    coalesce((lag(total_starts,10)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l10,
    coalesce((lag(total_starts,11)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l11,
    coalesce((lag(total_starts,12)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l12,
    coalesce((lag(total_starts,13)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l13,
    coalesce((lag(total_starts,14)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l14,
    coalesce((lag(total_starts,15)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l15,
    coalesce((lag(total_starts,16)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l16,
    coalesce((lag(total_starts,17)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l17,
    coalesce((lag(total_starts,18)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l18,
    coalesce((lag(total_starts,19)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l19,
    coalesce((lag(total_starts,20)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l20,
    coalesce((lag(total_starts,21)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l21,
    coalesce((lag(total_starts,22)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l22,
    coalesce((lag(total_starts,23)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l23,
    coalesce((lag(total_starts,24)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l24,
    coalesce((lag(total_starts,25)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l25,
    coalesce((lag(total_starts,26)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l26,
    coalesce((lag(total_starts,27)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l27,
    coalesce((lag(total_starts,28)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l28,
    coalesce((lag(total_starts,29)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l29,
    coalesce((lag(total_starts,30)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l30,
    coalesce((lag(total_starts,31)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l31,
    coalesce((lag(total_starts,32)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l32,
    coalesce((lag(total_starts,33)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l33,
    coalesce((lag(total_starts,34)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l34,
    coalesce((lag(total_starts,35)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l35,
    coalesce((lag(total_starts,36)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l36,
    coalesce((lag(total_starts,37)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l37,
    coalesce((lag(total_starts,38)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l38,
    coalesce((lag(total_starts,39)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l39,
    coalesce((lag(total_starts,40)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l40,
    coalesce((lag(total_starts,41)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l41,
    coalesce((lag(total_starts,42)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l42,
    coalesce((lag(total_starts,43)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l43,
    coalesce((lag(total_starts,44)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l44,
    coalesce((lag(total_starts,45)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l45,
    coalesce((lag(total_starts,46)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l46,
    coalesce((lag(total_starts,47)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l47,
    coalesce((lag(total_starts,48)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l48,
    coalesce((lag(total_starts,49)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l49,
    coalesce((lag(total_starts,50)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l50,
    coalesce((lag(total_starts,51)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l51,
    coalesce((lag(total_starts,52)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l52,
    coalesce((lag(total_starts,53)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l53,
        coalesce((lag(total_starts,54)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l54,
        coalesce((lag(total_starts,55)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l55,
        coalesce((lag(total_starts,56)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l56,
        coalesce((lag(total_starts,57)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l57,
        coalesce((lag(total_starts,58)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l58,
        coalesce((lag(total_starts,59)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l59,
        coalesce((lag(total_starts,60)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l60,
        coalesce((lag(total_starts,61)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l61,
        coalesce((lag(total_starts,62)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l62,
        coalesce((lag(total_starts,63)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l63,
        coalesce((lag(total_starts,64)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l64,
        coalesce((lag(total_starts,65)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l65,
        coalesce((lag(total_starts,66)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l66,
            coalesce((lag(total_starts,67)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l67,
            coalesce((lag(total_starts,68)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l68,
            coalesce((lag(total_starts,69)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l69,
    coalesce((lag(total_starts,70)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l70,
    coalesce((lag(total_starts,71)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l71,
    coalesce((lag(total_starts,72)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l72,
    coalesce((lag(total_starts,73)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l73,
    
        coalesce((lag(total_starts,74)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l74,
        coalesce((lag(total_starts,75)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l75,
        coalesce((lag(total_starts,76)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l76,
        coalesce((lag(total_starts,77)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l77,
        coalesce((lag(total_starts,78)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l78,
        coalesce((lag(total_starts,79)
    OVER (PARTITION BY signup_plan,Trial_Period ORDER BY Signup_month ASC)),0) AS total_starts_l79
    
     from LTV_stg2
     order by 2,1
)

select 
signup_plan,Trial_Period,
sum( Subs_Retained_1) as  Subs_Retained_1,
sum( Subs_Retained_2) as  Subs_Retained_2,
sum( Subs_Retained_3) as  Subs_Retained_3,
sum( Subs_Retained_4) as  Subs_Retained_4,
sum( Subs_Retained_5) as  Subs_Retained_5,
sum( Subs_Retained_6) as  Subs_Retained_6,
sum( Subs_Retained_7) as  Subs_Retained_7,
sum( Subs_Retained_8) as  Subs_Retained_8,
sum( Subs_Retained_9) as  Subs_Retained_9,
sum( Subs_Retained_10) as  Subs_Retained_10,
sum( Subs_Retained_11) as  Subs_Retained_11,
sum( Subs_Retained_12) as  Subs_Retained_12,

sum( Subs_Retained_13) as  Subs_Retained_13,
sum( Subs_Retained_14) as  Subs_Retained_14,
sum( Subs_Retained_15) as  Subs_Retained_15,
sum( Subs_Retained_16) as  Subs_Retained_16,
sum( Subs_Retained_17) as  Subs_Retained_17,
sum( Subs_Retained_18) as  Subs_Retained_18,
sum( Subs_Retained_19) as  Subs_Retained_19,
sum( Subs_Retained_20) as  Subs_Retained_20,
sum( Subs_Retained_21) as  Subs_Retained_21,
sum( Subs_Retained_22) as  Subs_Retained_22,
sum( Subs_Retained_23) as  Subs_Retained_23,
sum( Subs_Retained_24) as  Subs_Retained_24,
sum( Subs_Retained_25) as  Subs_Retained_25,
sum( Subs_Retained_26) as  Subs_Retained_26,
sum( Subs_Retained_27) as  Subs_Retained_27,
sum( Subs_Retained_28) as  Subs_Retained_28,
sum( Subs_Retained_29) as  Subs_Retained_29,
sum( Subs_Retained_30) as  Subs_Retained_30,
sum( Subs_Retained_31) as  Subs_Retained_31,
sum( Subs_Retained_32) as  Subs_Retained_32,
sum( Subs_Retained_33) as  Subs_Retained_33,
sum( Subs_Retained_34) as  Subs_Retained_34,
sum( Subs_Retained_35) as  Subs_Retained_35,
sum( Subs_Retained_36) as  Subs_Retained_36,
sum( Subs_Retained_37) as  Subs_Retained_37,
sum( Subs_Retained_38) as  Subs_Retained_38,
sum( Subs_Retained_39) as  Subs_Retained_39,
sum( Subs_Retained_40) as  Subs_Retained_40,
sum( Subs_Retained_41) as  Subs_Retained_41,
sum( Subs_Retained_42) as  Subs_Retained_42,
sum( Subs_Retained_43) as  Subs_Retained_43,
sum( Subs_Retained_44) as  Subs_Retained_44,
sum( Subs_Retained_45) as  Subs_Retained_45,
sum( Subs_Retained_46) as  Subs_Retained_46,
sum( Subs_Retained_47) as  Subs_Retained_47,
sum( Subs_Retained_48) as  Subs_Retained_48,
sum( Subs_Retained_49) as  Subs_Retained_49,
sum( Subs_Retained_50) as  Subs_Retained_50,
sum( Subs_Retained_51) as  Subs_Retained_51,
sum( Subs_Retained_52) as  Subs_Retained_52,
sum( Subs_Retained_53) as  Subs_Retained_53,
sum( Subs_Retained_54) as  Subs_Retained_54,
sum( Subs_Retained_55) as  Subs_Retained_55,
sum( Subs_Retained_56) as  Subs_Retained_56,
sum( Subs_Retained_57) as  Subs_Retained_57,
sum( Subs_Retained_58) as  Subs_Retained_58,
sum( Subs_Retained_59) as  Subs_Retained_59,
sum( Subs_Retained_60) as  Subs_Retained_60,
sum( Subs_Retained_61) as  Subs_Retained_61,
sum( Subs_Retained_62) as  Subs_Retained_62,
sum( Subs_Retained_63) as  Subs_Retained_63,
sum( Subs_Retained_64) as  Subs_Retained_64,
sum( Subs_Retained_65) as  Subs_Retained_65,
sum( Subs_Retained_66) as  Subs_Retained_66,
sum( Subs_Retained_67) as  Subs_Retained_67,
sum( Subs_Retained_68) as  Subs_Retained_68,
sum( Subs_Retained_69) as  Subs_Retained_69,
sum( Subs_Retained_70) as  Subs_Retained_70,
sum( Subs_Retained_71) as  Subs_Retained_71,
sum( Subs_Retained_72) as  Subs_Retained_72,
sum( Subs_Retained_73) as  Subs_Retained_73,
sum( Subs_Retained_74) as  Subs_Retained_74,
sum( Subs_Retained_75) as  Subs_Retained_75,
sum( Subs_Retained_76) as  Subs_Retained_76,
sum( Subs_Retained_77) as  Subs_Retained_77,
sum( Subs_Retained_78) as  Subs_Retained_78,
sum( Subs_Retained_79) as  Subs_Retained_79
from LTV_stg2
group by 1,2
UNION ALL

select 
signup_plan,Trial_Period,
sum( total_starts) as  total_starts,
sum( total_starts_l1) as  total_starts_l1,
sum( total_starts_l2) as  total_starts_l2,
sum( total_starts_l3) as  total_starts_l3,
sum( total_starts_l4) as  total_starts_l4,
sum( total_starts_l5) as  total_starts_l5,
sum( total_starts_l6) as  total_starts_l6,
sum( total_starts_l7) as  total_starts_l7,
sum( total_starts_l8) as  total_starts_l8,
sum( total_starts_l9) as  total_starts_l9,
sum( total_starts_l10) as  total_starts_l10,
sum( total_starts_l11) as  total_starts_l11,

sum( total_starts_l12) as  total_starts_l12,
sum( total_starts_l13) as  total_starts_l13,
sum( total_starts_l14) as  total_starts_l14,
sum( total_starts_l15) as  total_starts_l15,
sum( total_starts_l16) as  total_starts_l16,
sum( total_starts_l17) as  total_starts_l17,
sum( total_starts_l18) as  total_starts_l18,
sum( total_starts_l19) as  total_starts_l19,
sum( total_starts_l20) as  total_starts_l20,
sum( total_starts_l21) as  total_starts_l21,
sum( total_starts_l22) as  total_starts_l22,
sum( total_starts_l23) as  total_starts_l23,
sum( total_starts_l24) as  total_starts_l24,
sum( total_starts_l25) as  total_starts_l25,
sum( total_starts_l26) as  total_starts_l26,
sum( total_starts_l27) as  total_starts_l27,
sum( total_starts_l28) as  total_starts_l28,
sum( total_starts_l29) as  total_starts_l29,
sum( total_starts_l30) as  total_starts_l30,
sum( total_starts_l31) as  total_starts_l31,
sum( total_starts_l32) as  total_starts_l32,
sum( total_starts_l33) as  total_starts_l33,
sum( total_starts_l34) as  total_starts_l34,
sum( total_starts_l35) as  total_starts_l35,
sum( total_starts_l36) as  total_starts_l36,
sum( total_starts_l37) as  total_starts_l37,
sum( total_starts_l38) as  total_starts_l38,
sum( total_starts_l39) as  total_starts_l39,
sum( total_starts_l40) as  total_starts_l40,
sum( total_starts_l41) as  total_starts_l41,
sum( total_starts_l42) as  total_starts_l42,
sum( total_starts_l43) as  total_starts_l43,
sum( total_starts_l44) as  total_starts_l44,
sum( total_starts_l45) as  total_starts_l45,
sum( total_starts_l46) as  total_starts_l46,
sum( total_starts_l47) as  total_starts_l47,
sum( total_starts_l48) as  total_starts_l48,
sum( total_starts_l49) as  total_starts_l49,
sum( total_starts_l50) as  total_starts_l50,
sum( total_starts_l51) as  total_starts_l51,
sum( total_starts_l52) as  total_starts_l52,
sum( total_starts_l53) as  total_starts_l53,
sum( total_starts_l54) as  total_starts_l54,
sum( total_starts_l55) as  total_starts_l55,
sum( total_starts_l56) as  total_starts_l56,
sum( total_starts_l57) as  total_starts_l57,
sum( total_starts_l58) as  total_starts_l58,
sum( total_starts_l59) as  total_starts_l59,
sum( total_starts_l60) as  total_starts_l60,
sum( total_starts_l61) as  total_starts_l61,
sum( total_starts_l62) as  total_starts_l62,
sum( total_starts_l63) as  total_starts_l63,
sum( total_starts_l64) as  total_starts_l64,
sum( total_starts_l65) as  total_starts_l65,
sum( total_starts_l66) as  total_starts_l66,
sum( total_starts_l67) as  total_starts_l67,
sum( total_starts_l68) as  total_starts_l68,
sum( total_starts_l69) as  total_starts_l69,
sum( total_starts_l70) as  total_starts_l70,
sum( total_starts_l71) as  total_starts_l71,
sum( total_starts_l72) as  total_starts_l72,
sum( total_starts_l73) as  total_starts_l73,
sum( total_starts_l74) as  total_starts_l74,
sum( total_starts_l75) as  total_starts_l75,
sum( total_starts_l76) as  total_starts_l76,
sum( total_starts_l77) as  total_starts_l77,
sum( total_starts_l78) as  total_starts_l78


from LTV_stg3
group by 1,2
order by 1,2,3"""

In [32]:
def get_data_tp(client,till_date='2021-04-01', start_date='2014-10-01', end_date='2021-3-01'):
    sql = query
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("till_date", "DATE", till_date),
            bigquery.ScalarQueryParameter("start_date", "DATE", start_date),
            bigquery.ScalarQueryParameter("end_date", "DATE", end_date)
        ]
    )
    df = client.query(sql, job_config=job_config).to_dataframe()
    return df
def renaming_columns_tp(df):
    for i in df.index:
        if i%2!=0:
            df['Trial_Period'][i]=df['Trial_Period'][i]+'- Total Starts'
    return df

def cal_overall_df_tp(df):
    trial_period=['1 Month Free','1 Week Free','3 Month Free', '50% off 1 Month','50% off 3 Month','Direct-to-Paid']
    temp=pd.DataFrame()
    for i in range(len(trial_period)):
        filter_df=df[df['Trial_Period'].str.endswith(trial_period[i])].reset_index(drop=True)
        total = filter_df.apply(np.sum)
        total['signup_plan'] = 'OVERALL'
        filter_df=filter_df.append(pd.DataFrame(total.values, index=total.keys()).T, ignore_index=True)
        filter_df['Trial_Period'][2]=filter_df['Trial_Period'][2][0:int(len(filter_df['Trial_Period'][2])/2)]

        total_starts_df=df[df['Trial_Period'].str.endswith(trial_period[i]+'- Total Starts')].reset_index(drop=True)
        total = total_starts_df.apply(np.sum)
        total['signup_plan'] = 'OVERALL'
        total_starts_df=total_starts_df.append(pd.DataFrame(total.values, index=total.keys()).T, ignore_index=True)
        total_starts_df['Trial_Period'][2]=total_starts_df['Trial_Period'][2][0:int(len(total_starts_df['Trial_Period'][2])/2)]

        df1=df[df['Trial_Period'].str.endswith(trial_period[i])]
        df2=df[df['Trial_Period'].str.endswith(trial_period[i]+'- Total Starts')]
        df3=filter_df[filter_df['signup_plan'].str.endswith('OVERALL')]
        df4=total_starts_df[total_starts_df['signup_plan'].str.endswith('OVERALL')]
        new_df=pd.concat([df1, df2,df3,df4]).reset_index(drop=True)
        temp=pd.concat([temp,new_df]).reset_index(drop=True)
    add_remaining=df[df['Trial_Period'].str.contains('2-Day Free') | df['Trial_Period'].str.contains('3-Day Free') |df['Trial_Period'].str.contains('2 Month Free') ]
    new_df=pd.concat([temp,add_remaining]).reset_index(drop=True)
    return new_df
def calc_weighted_avg_retention_rate_tp(df):
    weighted_avg_retention_Rate = []
    for i in range(1, 67):
        if (df['Subs_Retained_' + str(i)][0] != 0 and df['Subs_Retained_' + str(i)][1] != 0):
            weighted_avg_retention_Rate.append(round(df['Subs_Retained_' + str(i)][0] / df['Subs_Retained_' + str(i)][1] * 100, 2))
        else:
            weighted_avg_retention_Rate.append(0)
    return weighted_avg_retention_Rate;

def calc_retained_from_previous_month_tp(df):
    calc_wt_avg_ret_rt = calc_weighted_avg_retention_rate_tp(df)
    retained_from_previous_month = []
    for i in range(0, 65):
        if (calc_wt_avg_ret_rt[i + 1]!=0 and calc_wt_avg_ret_rt[i]!=0 and calc_wt_avg_ret_rt[i + 1] / calc_wt_avg_ret_rt[i] < 1):
            retained_from_previous_month.append(round(calc_wt_avg_ret_rt[i + 1] / calc_wt_avg_ret_rt[i] * 100, 2))

        elif (calc_wt_avg_ret_rt[i + 1]!=0 and calc_wt_avg_ret_rt[i] and calc_wt_avg_ret_rt[i + 1] / calc_wt_avg_ret_rt[i] >= 1):
            if i!=0:
                retained_from_previous_month.append(retained_from_previous_month[i - 1])
            else:
                retained_from_previous_month.append(0)
        else:
            retained_from_previous_month.append(0)

    return retained_from_previous_month

def calc_avg_retain_first_12_month_tp(df):
    ret_pre_month = calc_retained_from_previous_month_tp(df)
    return round(np.average(ret_pre_month[0:12]), 2)

def calc_conf_rev_CF():
    return 0.71*9.99

def calc_conf_rev(plan_cd):
    if plan_cd=='LC':
        return 0.71*5.99
    elif plan_cd=='OVERALL':
        return 0.71*7.03

def calc_conf_w_ad_rev(plan_cd):
     if plan_cd=='LC':
        return 1.95
     elif plan_cd=='OVERALL':
        return 0.734*1.95

def calc_projected_retenion_month_tp(df):
    projected_retenion_month = []
    wt_avg_ret_rt = calc_weighted_avg_retention_rate_tp(df)
    avg_ret_12_mths = calc_avg_retain_first_12_month_tp(df)
    for i in range(0, 60):
        if  wt_avg_ret_rt[i] == 0:
            projected_retenion_month.append(projected_retenion_month[i - 1] * avg_ret_12_mths/100)
        elif i == 0 and wt_avg_ret_rt[i] == 0:  # added an extra check seems broken in excel
            projected_retenion_month.append(avg_ret_12_mths)
        else:
            projected_retenion_month.append(wt_avg_ret_rt[i])
    return projected_retenion_month

def calc_exp_dur_subs_mnths_and_LTV_CF_tp(df,given_inp=False):
    projected_retenion_month = calc_projected_retenion_month_tp(df)
    duration = 0
    if given_inp == True:
        print('options 3M, 6M, 9M, 1Y, 2Y, 3Y, 4Y, 5Y, ALL')
        duration = input('Enter the Duration from above options')

    if duration == '3M':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:3]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:3]) / 100) * calc_conf_rev_CF(), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev

    elif duration == '6M':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:6]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:6]) / 100) * calc_conf_rev_CF(), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev

    elif duration == '9M':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:9]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:9]) / 100) * calc_conf_rev_CF(), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev

    elif duration == '1Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:12]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:12]) / 100) * calc_conf_rev_CF(), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev

    elif duration == '2Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:24]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:24]) / 100) * calc_conf_rev_CF(), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev

    elif duration == '3Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:36]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:36]) / 100) * calc_conf_rev_CF(), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev

    elif duration == '4Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:48]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:48]) / 100) * calc_conf_rev_CF(), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev

    elif duration == '5Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:60]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:60]) / 100) * calc_conf_rev_CF(), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev

    elif duration == 'ALL' or duration == 0:
        exp_dur_subs_mnths = []
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:3]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:6]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:9]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:12]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:24]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:36]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:48]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:60]) / 100, 1))
        LTV_wo_ad_Rev = []
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:3]) / 100) * calc_conf_rev_CF(), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:6]) / 100) * calc_conf_rev_CF(), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:9]) / 100) * calc_conf_rev_CF(), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:12]) / 100) * calc_conf_rev_CF(), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:24]) / 100) * calc_conf_rev_CF(), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:36]) / 100) * calc_conf_rev_CF(), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:48]) / 100) * calc_conf_rev_CF(), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:60]) / 100) * calc_conf_rev_CF(), 2))
        return exp_dur_subs_mnths, LTV_wo_ad_Rev

    else:
        print("Please select appropiate option")
        return calc_exp_dur_subs_mnths_LTV_w_wo_revenue(df)

def calc_exp_dur_subs_mnths_and_LTV_LC_tp(df,plan_cd, given_inp=False):
    projected_retenion_month = calc_projected_retenion_month_tp(df)
    duration = 0
    if given_inp == True:
        print('options 3M, 6M, 9M, 1Y, 2Y, 3Y, 4Y, 5Y, ALL')
        duration = input('Enter the Duration from above options')

    if duration == '3M':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:3]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:3]) / 100) * calc_conf_rev(plan_cd), 2)
        LTV_w_ad_Rev = round(LTV_wo_ad_Rev + (sum(projected_retenion_month[0:3]) / 100) * calc_conf_w_ad_rev(plan_cd), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev, LTV_w_ad_Rev

    elif duration == '6M':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:6]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:6]) / 100) * calc_conf_rev(plan_cd), 2)
        LTV_w_ad_Rev = round(LTV_wo_ad_Rev + (sum(projected_retenion_month[0:6]) / 100) * calc_conf_w_ad_rev(plan_cd), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev, LTV_w_ad_Rev

    elif duration == '9M':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:9]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:9]) / 100) * calc_conf_rev(plan_cd), 2)
        LTV_w_ad_Rev = round(LTV_wo_ad_Rev + (sum(projected_retenion_month[0:9]) / 100) * calc_conf_w_ad_rev(plan_cd), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev, LTV_w_ad_Rev

    elif duration == '1Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:12]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:12]) / 100) * calc_conf_rev(plan_cd), 2)
        LTV_w_ad_Rev = round(LTV_wo_ad_Rev[3] + (sum(projected_retenion_month[0:12]) / 100) * calc_conf_w_ad_rev(plan_cd), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev, LTV_w_ad_Rev

    elif duration == '2Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:24]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:24]) / 100) * calc_conf_rev(plan_cd), 2)
        LTV_w_ad_Rev = round(LTV_wo_ad_Rev[4] + (sum(projected_retenion_month[0:24]) / 100) * calc_conf_w_ad_rev(plan_cd), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev, LTV_w_ad_Rev

    elif duration == '3Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:36]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:36]) / 100) * calc_conf_rev(plan_cd), 2)
        LTV_w_ad_Rev = round(LTV_wo_ad_Rev[5] + (sum(projected_retenion_month[0:36]) / 100) * calc_conf_w_ad_rev(plan_cd), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev, LTV_w_ad_Rev

    elif duration == '4Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:48]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:48]) / 100) * calc_conf_rev(plan_cd), 2)
        LTV_w_ad_Rev = round(LTV_wo_ad_Rev[6] + (sum(projected_retenion_month[0:48]) / 100) * calc_conf_w_ad_rev(plan_cd), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev, LTV_w_ad_Rev

    elif duration == '5Y':
        exp_dur_subs_mnths = round(sum(projected_retenion_month[0:60]) / 100, 1)
        LTV_wo_ad_Rev = round((sum(projected_retenion_month[0:60]) / 100) * calc_conf_rev(plan_cd), 2)
        LTV_w_ad_Rev = round(LTV_wo_ad_Rev[7] + (sum(projected_retenion_month[0:60]) / 100) * calc_conf_w_ad_rev(plan_cd), 2)
        return exp_dur_subs_mnths, LTV_wo_ad_Rev, LTV_w_ad_Rev

    elif duration == 'ALL' or duration == 0:
        exp_dur_subs_mnths = []
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:3]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:6]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:9]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:12]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:24]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:36]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:48]) / 100, 1))
        exp_dur_subs_mnths.append(round(sum(projected_retenion_month[0:60]) / 100, 1))
        LTV_wo_ad_Rev = []
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:3]) / 100) * calc_conf_rev(plan_cd), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:6]) / 100) * calc_conf_rev(plan_cd), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:9]) / 100) * calc_conf_rev(plan_cd), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:12]) / 100) * calc_conf_rev(plan_cd), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:24]) / 100) * calc_conf_rev(plan_cd), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:36]) / 100) * calc_conf_rev(plan_cd), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:48]) / 100) * calc_conf_rev(plan_cd), 2))
        LTV_wo_ad_Rev.append(round((sum(projected_retenion_month[0:60]) / 100) * calc_conf_rev(plan_cd), 2))
        LTV_w_ad_Rev = []
        LTV_w_ad_Rev.append(round(LTV_wo_ad_Rev[0] + (sum(projected_retenion_month[0:3]) / 100) * calc_conf_w_ad_rev(plan_cd), 2))
        LTV_w_ad_Rev.append(round(LTV_wo_ad_Rev[1] + (sum(projected_retenion_month[0:6]) / 100) * calc_conf_w_ad_rev(plan_cd), 2))
        LTV_w_ad_Rev.append(round(LTV_wo_ad_Rev[2] + (sum(projected_retenion_month[0:9]) / 100) * calc_conf_w_ad_rev(plan_cd), 2))
        LTV_w_ad_Rev.append(round(LTV_wo_ad_Rev[3] + (sum(projected_retenion_month[0:12]) / 100) * calc_conf_w_ad_rev(plan_cd), 2))
        LTV_w_ad_Rev.append(round(LTV_wo_ad_Rev[4] + (sum(projected_retenion_month[0:24]) / 100) * calc_conf_w_ad_rev(plan_cd), 2))
        LTV_w_ad_Rev.append(round(LTV_wo_ad_Rev[5] + (sum(projected_retenion_month[0:36]) / 100) * calc_conf_w_ad_rev(plan_cd), 2))
        LTV_w_ad_Rev.append(round(LTV_wo_ad_Rev[6] + (sum(projected_retenion_month[0:48]) / 100) * calc_conf_w_ad_rev(plan_cd), 2))
        LTV_w_ad_Rev.append(round(LTV_wo_ad_Rev[7] + (sum(projected_retenion_month[0:60]) / 100) * calc_conf_w_ad_rev(plan_cd), 2))
        return exp_dur_subs_mnths, LTV_wo_ad_Rev, LTV_w_ad_Rev

def calc_all_LTV_tp(df_n):
    final_output=pd.DataFrame()
    trial_period=['2-Day Free','3-Day Free','1 Week Free','1 Month Free','3 Month Free','50% off 1 Month','50% off 3 Month','Direct-to-Paid']
    plan_cd=['CF','LC','OVERALL']

    for j in range(len(plan_cd)):
        for i in range(len(trial_period)):
            if plan_cd[j]=='CF':
                this_df=df_n[df_n['signup_plan'].str.contains(plan_cd[j]) & df_n['Trial_Period'].str.startswith(trial_period[i])].reset_index(drop=True)
                _,ltv_amt=calc_exp_dur_subs_mnths_and_LTV_CF_tp(this_df)
                temp_dict={"trial_period" : [trial_period[i]],"plan_type" : [plan_cd[j]], "year_1_amt":[ltv_amt[3]],"year_3_amt":[ltv_amt[5]],"year_5_amt":[ltv_amt[7]]}
                temp_df=pd.DataFrame.from_dict(temp_dict,orient='columns')
                final_output=round(pd.concat([final_output,temp_df]))
            elif plan_cd[j]=='LC':
                if trial_period[i]=='2-Day Free' or trial_period[i]=='3-Day Free':
                    temp_dict={"trial_period" : [trial_period[i]],"plan_type" : [plan_cd[j]], "year_1_amt":[0.0],"year_3_amt":[0.0],"year_5_amt":[0.0]}
                    temp_df=pd.DataFrame.from_dict(temp_dict,orient='columns')
                    final_output=round(pd.concat([final_output,temp_df]))
                else:
                    this_df=df_n[df_n['signup_plan'].str.contains(plan_cd[j]) & df_n['Trial_Period'].str.startswith(trial_period[i])].reset_index(drop=True)
                    _,__,ltv_amt=calc_exp_dur_subs_mnths_and_LTV_LC_tp(this_df,plan_cd[j])
                    temp_dict={"trial_period" : [trial_period[i]],"plan_type" : [plan_cd[j]], "year_1_amt":[ltv_amt[3]],"year_3_amt":[ltv_amt[5]],"year_5_amt":[ltv_amt[7]]}
                    temp_df=pd.DataFrame.from_dict(temp_dict,orient='columns')
                    final_output=round(pd.concat([final_output,temp_df]))
            elif plan_cd[j]=='OVERALL':
                if trial_period[i]=='2-Day Free' or trial_period[i]=='3-Day Free':
                    this_df=df_n[df_n['signup_plan'].str.contains('CF') & df_n['Trial_Period'].str.startswith(trial_period[i])].reset_index(drop=True)
                    _,ltv_amt=calc_exp_dur_subs_mnths_and_LTV_CF_tp(this_df)
                    temp_dict={"trial_period" : [trial_period[i]],"plan_type" : [plan_cd[j]], "year_1_amt":[ltv_amt[3]],"year_3_amt":[ltv_amt[5]],"year_5_amt":[ltv_amt[7]]}
                    temp_df=pd.DataFrame.from_dict(temp_dict,orient='columns')
                    final_output=round(pd.concat([final_output,temp_df]))
                else:
                    this_df=df_n[df_n['signup_plan'].str.contains(plan_cd[j]) & df_n['Trial_Period'].str.startswith(trial_period[i])].reset_index(drop=True)
                    _,__,ltv_amt=calc_exp_dur_subs_mnths_and_LTV_LC_tp(this_df,plan_cd[j])
                    temp_dict={"trial_period" : [trial_period[i]],"plan_type" : [plan_cd[j]], "year_1_amt":[ltv_amt[3]],"year_3_amt":[ltv_amt[5]],"year_5_amt":[ltv_amt[7]]}
                    temp_df=pd.DataFrame.from_dict(temp_dict,orient='columns')
                    final_output=round(pd.concat([final_output,temp_df]))
    return final_output.reset_index(drop=True)

def add_quarter_date(temp,till_date):
    temp['day_dt'] = till_date
    cols = temp.columns.tolist()
    cols = cols[-1:] + cols[:-1]
    output = temp[cols]
    return output
def add_current_date(temp):
    from datetime import date
    today = date.today()
    temp['dw_create_dt'] = pd.to_datetime(date.today())
    return temp

In [33]:
from google.cloud import bigquery
client = bigquery.Client('ltvsubscribers')
df=get_data_tp(client)

/Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

,signup_plan,Trial_Period,Subs_Retained_1,Subs_Retained_2,Subs_Retained_3,Subs_Retained_4,Subs_Retained_5,Subs_Retained_6,Subs_Retained_7,Subs_Retained_8,...,Subs_Retained_70,Subs_Retained_71,Subs_Retained_72,Subs_Retained_73,Subs_Retained_74,Subs_Retained_75,Subs_Retained_76,Subs_Retained_77,Subs_Retained_78,Subs_Retained_79
0,CF-Monthly,1 Month Free,1755616,599724,442902,357477,302415,244401,217750,198856,...,0,0,0,0,0,0,0,0,0,0
1,CF-Monthly,1 Month Free,1810858,1123730,1115931,1110696,1096563,1013245,1000997,989993,...,0,0,0,0,0,0,0,0,0,0
2,CF-Monthly,1 Week Free,1984824,1421524,1059135,833992,666110,574382,488269,421523,...,0,0,0,0,0,0,0,0,0,0
3,CF-Monthly,1 Week Free,3302599,3290087,2988956,2796141,2603926,2511531,2368361,2217454,...,0,0,0,0,0,0,0,0,0,0
4,CF-Monthly,2-Day Free,69196,61298,53857,48744,44816,39932,36414,33848,...,0,0,0,0,0,0,0,0,0,0
5,CF-Monthly,2-Day Free,86413,86413,86413,86413,86413,86413,86413,86413,...,0,0,0,0,0,0,0,0,0,0
6,CF-Monthly,3 Month Free,18804,40492,40482,29459,22404,18590,16079,14304,...,0,0,0,0,0,0,0,0,0,0
7,CF-Monthly,3 Month Free,52530,52530,52530,52530,52530,52530,52530,52530,...,0,0,0,0,0,0,0,0,0,0
8,CF-Monthly,3-Day Free,64867,45978,38649,33613,29869,26938,24578,22519,...,0,0,0,0,0,0,0,0,0,0
9,CF-Monthly,3-Day Free,109448,109448,109448,109448,109448,109448,109448,109448,...,0,0,0,0,0,0,0,0,0,0
10,CF-Monthly,50% off 1 Month,389,278,237,204,175,157,135,120,...,0,0,0,0,0,0,0,0,0,0
11,CF-Monthly,50% off 1 Month,509,509,509,509,509,508,508,508,...,0,0,0,0,0,0,0,0,0,0
12,CF-Monthly,50% off 3 Month,1777,1340,1152,912,766,666,593,534,...,0,0,0,0,0,0,0,0,0,0
13,CF-Monthly,50% off 3 Month,1924,1924,1924,1924,1922,1922,1921,1920,...,0,0,0,0,0,0,0,0,0,0
14,CF-Monthly,Direct-to-Paid,1114306,799435,659216,548899,458635,396225,343327,306487,...,0,0,0,0,0,0,0,0,0,0
15,CF-Monthly,Direct-to-Paid,1160557,1104049,1056159,1013500,968201,937460,895418,863636,...,0,0,0,0,0,0,0,0,0,0
16,LC-Monthly,1 Month Free,2694878,1323496,1015849,851775,740720,621726,561538,514564,...,404,189,0,0,0,0,0,0,0,0
17,LC-Monthly,1 Month Free,2894821,2173157,2162249,2142460,2118980,1997106,1970428,1938982,...,3410,2038,0,0,0,0,0,0,0,0
18,LC-Monthly,1 Week Free,7294932,5575600,4419823,3689168,3138170,2770618,2421686,2154437,...,10753,3535,484,0,0,22,0,0,0,0
19,LC-Monthly,1 Week Free,11066703,11052285,10385076,10051765,9721338,9549959,9232096,8907233,...,491463,363132,304689,266738,237683,184010,138851,86889,28643,0
20,LC-Monthly,2 Month Free,21753,18166,11613,9146,7923,7093,6358,5758,...,0,0,0,0,0,0,0,0,0,0
21,LC-Monthly,2 Month Free,21840,21840,21840,21840,21840,21840,21840,21840,...,0,0,0,0,0,0,0,0,0,0
22,LC-Monthly,3 Month Free,2508,27784,27736,18339,15464,13678,12344,11218,...,0,0,0,0,0,0,0,0,0,0
23,LC-Monthly,3 Month Free,27876,27876,27876,27876,27876,27876,27876,27876,...,0,0,0,0,0,0,0,0,0,0
24,LC-Monthly,50% off 1 Month,1397,730,569,481,423,372,328,288,...,0,0,0,0,0,0,0,0,0,0
25,LC-Monthly,50% off 1 Month,1427,1427,1427,1426,1426,1426,1426,1426,...,0,0,0,0,0,0,0,0,0,0
26,LC-Monthly,50% off 3 Month,4828,3298,2715,2182,1839,1612,1435,1293,...,0,0,0,0,0,0,0,0,0,0
27,LC-Monthly,50% off 3 Month,5111,5111,5110,5109,5106,5105,5103,5098,...,0,0,0,0,0,0,0,0,0,0
28,LC-Monthly,Direct-to-Paid,2694252,1972965,1638734,1383132,1171260,1015060,861803,753219,...,23030,22404,21622,18487,15777,13160,10067,7011,2958,0
29,LC-Monthly,Direct-to-Paid,2793780,2703408,2566546,2469528,2385050,2314888,2195598,2098319,...,190573,186122,179171,144090,116879,90970,65625,43369,15932,0

In [35]:
df2=pd.read_csv('/Users/agupt0607/Documents/LTV_automation/old_data/LTV_by_trial_Period/LTV_by_Trial_Period-2021-04-01.csv')
# till_date='2021-04-01'
# df_new=renaming_columns_tp(df)
# df_n=cal_overall_df_tp(df_new)
# temp=calc_all_LTV_tp(df_n)
# fin=add_quarter_date(temp,till_date)
# output=add_current_date(fin)
# output
df2

,signup_plan,Trial_Period,Subs_Retained_1,Subs_Retained_2,Subs_Retained_3,Subs_Retained_4,Subs_Retained_5,Subs_Retained_6,Subs_Retained_7,Subs_Retained_8,...,Subs_Retained_70,Subs_Retained_71,Subs_Retained_72,Subs_Retained_73,Subs_Retained_74,Subs_Retained_75,Subs_Retained_76,Subs_Retained_77,Subs_Retained_78,Subs_Retained_79
0,CF-Monthly,1 Month Free,1755615,599722,442900,357475,302412,244397,217746,198852,...,0,0,0,0,0,0,0,0,0,0
1,CF-Monthly,1 Month Free,1810857,1123730,1115931,1110696,1096563,1013245,1000997,989993,...,0,0,0,0,0,0,0,0,0,0
2,CF-Monthly,1 Week Free,1984822,1421519,1059130,833985,666104,574376,488262,421516,...,0,0,0,0,0,0,0,0,0,0
3,CF-Monthly,1 Week Free,3302599,3290087,2988956,2796141,2603926,2511531,2368361,2217454,...,0,0,0,0,0,0,0,0,0,0
4,CF-Monthly,2-Day Free,69196,61298,53857,48744,44816,39932,36414,33848,...,0,0,0,0,0,0,0,0,0,0
5,CF-Monthly,2-Day Free,86413,86413,86413,86413,86413,86413,86413,86413,...,0,0,0,0,0,0,0,0,0,0
6,CF-Monthly,3 Month Free,18804,40492,40482,29459,22404,18590,16079,14304,...,0,0,0,0,0,0,0,0,0,0
7,CF-Monthly,3 Month Free,52530,52530,52530,52530,52530,52530,52530,52530,...,0,0,0,0,0,0,0,0,0,0
8,CF-Monthly,3-Day Free,64867,45978,38649,33613,29869,26938,24578,22519,...,0,0,0,0,0,0,0,0,0,0
9,CF-Monthly,3-Day Free,109448,109448,109448,109448,109448,109448,109448,109448,...,0,0,0,0,0,0,0,0,0,0
10,CF-Monthly,50% off 1 Month,389,278,237,204,175,157,135,120,...,0,0,0,0,0,0,0,0,0,0
11,CF-Monthly,50% off 1 Month,509,509,509,509,509,508,508,508,...,0,0,0,0,0,0,0,0,0,0
12,CF-Monthly,50% off 3 Month,1777,1340,1152,912,766,666,593,534,...,0,0,0,0,0,0,0,0,0,0
13,CF-Monthly,50% off 3 Month,1924,1924,1924,1924,1922,1922,1921,1920,...,0,0,0,0,0,0,0,0,0,0
14,CF-Monthly,Direct-to-Paid,1114304,799434,659214,548896,458631,396220,343322,306483,...,0,0,0,0,0,0,0,0,0,0
15,CF-Monthly,Direct-to-Paid,1160556,1104048,1056158,1013499,968200,937459,895417,863636,...,0,0,0,0,0,0,0,0,0,0
16,LC-Monthly,1 Month Free,2694878,1323494,1015846,851771,740715,621722,561534,514560,...,410,189,0,0,0,0,0,0,0,0
17,LC-Monthly,1 Month Free,2894821,2173157,2162249,2142460,2118980,1997106,1970428,1938982,...,3410,2038,0,0,0,0,0,0,0,0
18,LC-Monthly,1 Week Free,7294927,5575591,4419813,3689157,3138155,2770602,2421672,2154424,...,10926,3535,484,0,0,22,0,0,0,0
19,LC-Monthly,1 Week Free,11066703,11052285,10385076,10051765,9721338,9549959,9232096,8907233,...,491463,363132,304689,266738,237683,184010,138851,86889,28643,0
20,LC-Monthly,2 Month Free,21753,18166,11613,9146,7923,7093,6358,5758,...,0,0,0,0,0,0,0,0,0,0
21,LC-Monthly,2 Month Free,21840,21840,21840,21840,21840,21840,21840,21840,...,0,0,0,0,0,0,0,0,0,0
22,LC-Monthly,3 Month Free,2508,27784,27736,18339,15464,13678,12344,11218,...,0,0,0,0,0,0,0,0,0,0
23,LC-Monthly,3 Month Free,27876,27876,27876,27876,27876,27876,27876,27876,...,0,0,0,0,0,0,0,0,0,0
24,LC-Monthly,50% off 1 Month,1397,730,569,481,423,372,328,288,...,0,0,0,0,0,0,0,0,0,0
25,LC-Monthly,50% off 1 Month,1427,1427,1427,1426,1426,1426,1426,1426,...,0,0,0,0,0,0,0,0,0,0
26,LC-Monthly,50% off 3 Month,4828,3298,2715,2182,1839,1612,1435,1293,...,0,0,0,0,0,0,0,0,0,0
27,LC-Monthly,50% off 3 Month,5111,5111,5110,5109,5106,5105,5103,5098,...,0,0,0,0,0,0,0,0,0,0
28,LC-Monthly,Direct-to-Paid,2694251,1972961,1638730,1383130,1171258,1015058,861802,753218,...,23362,22404,21622,18487,15777,13160,10067,7011,2958,0
29,LC-Monthly,Direct-to-Paid,2793779,2703407,2566545,2469527,2385049,2314887,2195597,2098319,...,190573,186122,179171,144090,116879,90970,65625,43369,15932,0

In [59]:
tempo=df.iloc[:, 2:]-df2.iloc[:,2:]

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [15]:
#calc_weighted_avg_retention_rate(this_df)
#calc_retained_from_previous_month(this_df)
#calc_avg_retain_first_12_month_tp(this_df)
#calc_projected_retenion_month_tp(this_df)
#final_output.reset_index(drop=True)
output

,day_dt,plan_type,trial_period,year_1_amt,year_3_amt,year_5_amt,dw_create_dt
0,2021-04-01,CF,2-Day Free,41.0,78.0,92.0,2021-06-29
1,2021-04-01,CF,3-Day Free,24.0,41.0,53.0,2021-06-29
2,2021-04-01,CF,1 Week Free,23.0,37.0,45.0,2021-06-29
3,2021-04-01,CF,1 Month Free,27.0,41.0,43.0,2021-06-29
4,2021-04-01,CF,3 Month Free,33.0,52.0,52.0,2021-06-29
5,2021-04-01,CF,50% off 1 Month,29.0,39.0,40.0,2021-06-29
6,2021-04-01,CF,50% off 3 Month,35.0,47.0,48.0,2021-06-29
7,2021-04-01,CF,Direct-to-Paid,40.0,72.0,95.0,2021-06-29
8,2021-04-01,LC,2-Day Free,0.0,0.0,0.0,2021-06-29
9,2021-04-01,LC,3-Day Free,0.0,0.0,0.0,2021-06-29
10,2021-04-01,LC,1 Week Free,24.0,41.0,49.0,2021-06-29
11,2021-04-01,LC,1 Month Free,28.0,44.0,53.0,2021-06-29
12,2021-04-01,LC,3 Month Free,37.0,59.0,60.0,2021-06-29
13,2021-04-01,LC,50% off 1 Month,24.0,31.0,31.0,2021-06-29
14,2021-04-01,LC,50% off 3 Month,28.0,38.0,39.0,2021-06-29
15,2021-04-01,LC,Direct-to-Paid,36.0,60.0,72.0,2021-06-29
16,2021-04-01,OVERALL,2-Day Free,41.0,78.0,92.0,2021-06-29
17,2021-04-01,OVERALL,3-Day Free,24.0,41.0,53.0,2021-06-29
18,2021-04-01,OVERALL,1 Week Free,24.0,41.0,49.0,2021-06-29
19,2021-04-01,OVERALL,1 Month Free,27.0,44.0,53.0,2021-06-29
20,2021-04-01,OVERALL,3 Month Free,33.0,50.0,51.0,2021-06-29
21,2021-04-01,OVERALL,50% off 1 Month,25.0,33.0,33.0,2021-06-29
22,2021-04-01,OVERALL,50% off 3 Month,30.0,40.0,41.0,2021-06-29
23,2021-04-01,OVERALL,Direct-to-Paid,37.0,63.0,77.0,2021-06-29

In [16]:
output.to_gbq(destination_table='anit_sandbox.pt_ltv_subs_trial_period_by_quarter',
              project_id='ltvsubscribers',
              if_exists='replace',
           table_schema=[{'name': 'day_dt', 'type': 'DATE'}])
output

,day_dt,plan_type,trial_period,year_1_amt,year_3_amt,year_5_amt,dw_create_dt
0,2021-04-01,CF,2-Day Free,41.0,78.0,92.0,2021-06-29
1,2021-04-01,CF,3-Day Free,24.0,41.0,53.0,2021-06-29
2,2021-04-01,CF,1 Week Free,23.0,37.0,45.0,2021-06-29
3,2021-04-01,CF,1 Month Free,27.0,41.0,43.0,2021-06-29
4,2021-04-01,CF,3 Month Free,33.0,52.0,52.0,2021-06-29
5,2021-04-01,CF,50% off 1 Month,29.0,39.0,40.0,2021-06-29
6,2021-04-01,CF,50% off 3 Month,35.0,47.0,48.0,2021-06-29
7,2021-04-01,CF,Direct-to-Paid,40.0,72.0,95.0,2021-06-29
8,2021-04-01,LC,2-Day Free,0.0,0.0,0.0,2021-06-29
9,2021-04-01,LC,3-Day Free,0.0,0.0,0.0,2021-06-29
10,2021-04-01,LC,1 Week Free,24.0,41.0,49.0,2021-06-29
11,2021-04-01,LC,1 Month Free,28.0,44.0,53.0,2021-06-29
12,2021-04-01,LC,3 Month Free,37.0,59.0,60.0,2021-06-29
13,2021-04-01,LC,50% off 1 Month,24.0,31.0,31.0,2021-06-29
14,2021-04-01,LC,50% off 3 Month,28.0,38.0,39.0,2021-06-29
15,2021-04-01,LC,Direct-to-Paid,36.0,60.0,72.0,2021-06-29
16,2021-04-01,OVERALL,2-Day Free,41.0,78.0,92.0,2021-06-29
17,2021-04-01,OVERALL,3-Day Free,24.0,41.0,53.0,2021-06-29
18,2021-04-01,OVERALL,1 Week Free,24.0,41.0,49.0,2021-06-29
19,2021-04-01,OVERALL,1 Month Free,27.0,44.0,53.0,2021-06-29
20,2021-04-01,OVERALL,3 Month Free,33.0,50.0,51.0,2021-06-29
21,2021-04-01,OVERALL,50% off 1 Month,25.0,33.0,33.0,2021-06-29
22,2021-04-01,OVERALL,50% off 3 Month,30.0,40.0,41.0,2021-06-29
23,2021-04-01,OVERALL,Direct-to-Paid,37.0,63.0,77.0,2021-06-29

In [128]:
!pip install pandas_gbq

DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting pandas_gbq
  Downloading pandas_gbq-0.14.1-py3-none-any.whl (24 kB)
Requirement already satisfied: setuptools in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from pandas_gbq) (50.3.2)
Collecting pydata-google-auth
  Downloading pydata_google_auth-1.2.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: pandas>=0.20.1 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from pandas_gbq) (0.25.3)
Collecting google-auth-oauthlib
  Downloading google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from pandas_gbq) (1.28.0)
Requirement already satisfied: google-auth in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from pandas_gbq) (1.23.0)
Requirement already satisfied: google-resumable-media<2.0dev,>=0.6.0 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (1.1.0)
Requirement already satisfied: google-api-core<2.0dev,>=1.21.0 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (1.23.0)
Requirement already satisfied: google-cloud-core<2.0dev,>=1.4.1 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (1.4.4)
Requirement already satisfied: six<2.0.0dev,>=1.13.0 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (1.16.0)
Collecting google-cloud-bigquery-storage<2.0.0dev,>=1.0.0
  Downloading google_cloud_bigquery_storage-1.1.0-py2.py3-none-any.whl (135 kB)
     |████████████████████████████████| 135 kB 6.7 MB/s eta 0:00:01
Collecting grpcio<2.0dev,>=1.32.0
  Downloading grpcio-1.38.1-cp35-cp35m-macosx_10_10_intel.whl (6.9 MB)
     |████████████████████████████████| 6.9 MB 19.1 MB/s eta 0:00:01
Collecting pyarrow<2.0dev,>=1.0.0
  Downloading pyarrow-1.0.1-cp35-cp35m-macosx_10_9_intel.whl (11.0 MB)
     |████████████████████████████████| 11.0 MB 18.0 MB/s eta 0:00:01
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (2.25.1)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (1.52.0)
Requirement already satisfied: protobuf>=3.12.0 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (3.17.3)
Requirement already satisfied: pytz in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (2021.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-auth->pandas_gbq) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-auth->pandas_gbq) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-auth->pandas_gbq) (4.2.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (1.0.0)
Requirement already satisfied: cffi>=1.0.0 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (1.14.5)
Requirement already satisfied: pycparser in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (2.20)
Requirement already satisfied: numpy>=1.13.3 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from pandas>=0.20.1->pandas_gbq) (1.18.5)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from pandas>=0.20.1->pandas_gbq) (2.8.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from pyasn1-modules>=0.2.1->google-auth->pandas_gbq) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas_gbq) (1.26.5)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 25.2 MB/s eta 0:00:01
Installing collected packages: oauthlib, grpcio, requests-oauthlib, pyarrow, google-cloud-bigquery-storage, google-auth-oauthlib, pydata-google-auth, pandas-gbq
Successfully installed google-auth-oauthlib-0.4.1 google-cloud-bigquery-storage-1.1.0 grpcio-1.38.1 oauthlib-3.1.0 pandas-gbq-0.14.1 pyarrow-1.0.1 pydata-google-auth-1.2.0 requests-oauthlib-1.3.0

In [193]:
def check_data_exists(till_date='2031-04-01'):
    from google.cloud import bigquery
    client = bigquery.Client('ltvsubscribers')
    till_date='2031-04-01'
    sql="""
    select * from `ltvsubscribers.anit_sandbox.pt_ltv_subs_trial_period_by_quarter` 
    where day_dt= @till_date
    """
    job_config = bigquery.QueryJobConfig(
            query_parameters=[
                bigquery.ScalarQueryParameter("till_date", "TIMESTAMP", till_date),
            ]
        )
    df = client.query(sql, job_config=job_config).to_dataframe()
    
    if len(df)==0:
        return False
    else:
        return True

/Users/agupt0607/miniconda3/envs/env/lib/python3.5/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [195]:
len(df)

0